package com.bw.week1_one.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.week1_one.model.GetJson;

import com.bw.week1_one.database.GetJsonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig getJsonDaoConfig;

    private final GetJsonDao getJsonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        getJsonDaoConfig = daoConfigMap.get(GetJsonDao.class).clone();
        getJsonDaoConfig.initIdentityScope(type);

        getJsonDao = new GetJsonDao(getJsonDaoConfig, this);

        registerDao(GetJson.class, getJsonDao);
    }
    
    public void clear() {
        getJsonDaoConfig.clearIdentityScope();
    }

    public GetJsonDao getGetJsonDao() {
        return getJsonDao;
    }

}
